‎arch/arm64: Add Missing Configs * Android 16 QPR1 needed this configs
ERROR: files are incompatible: Runtime Info and framework compatibility matrix are incompatible: No compatible kernel requirement
(Kernel FCM version = 6).
For kernel requirements at matrix level 6, Kernel config errors:
Missing config CONFIG_RD_LZ4
Missing config CONFIG_STACKPROTECTOR
Missing config CONFIG_STACKPROTECTOR_STRONG
Missing config CONFIG_TRACE_GPU_NEM
Missing config CONFIG_CFI_CLANG
Missing config CONFIG_SHADOW_CALL_STACK
Missing config CONFIG_HAVE_MOVE_PMD
Missing config CONFIG_HAVE_MOVE_PUD
Missing config CONFIG_USERFAULTFD

Signed-off-by: Afifmomin <afifmomin123@gmail.com>